# site name
prefixName: Lonuslan
siteName: ブログ
# favicon and site master avatar
# favicon: /images/favicon.ico
favicon: https://img.lonuslan.com/lonuslan/20200414/SPGX7UvyK7aT.png
avatar: https://img.lonuslan.com/lonuslan/20200506/j4HihEh07glF.jpg
#avatar: /img/custom/avatar.jpg
#avatar: https://img.lonuslan.com/lonuslan/20200414/SPGX7UvyK7aT.png
url: https://www.lonuslan.xyz
description: It's better to burn out than to fade away!
#cdn: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6
cdn: https://cdn.jsdelivr.net/gh/lonuslan/cdn@1.8
pjax: 1
# 1开启
mathjax: 1

notice: 使用 hexo 搭建的博客网站， 部署在coding pages上...
lazyloadImg: https://cdn.jsdelivr.net/gh/lonuslan/cdn@1.8/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce },
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
#  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(1).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(2).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(3).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(4).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(5).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(6).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(7).jpg.webp
#  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(8).jpg.webp
  - https://img.lonuslan.com/lonuslan/20200120/AXsi94kr5YSl.jpg
  - https://img.lonuslan.com/lonuslan/20200120/o6RVlf8Tym1S.jpg
  - https://img.lonuslan.com/lonuslan/20200120/4Xw4pJJ6wA7X.jpg
  - https://img.lonuslan.com/lonuslan/20200120/d4yH2omtFThg.jpg
  - https://img.lonuslan.com/lonuslan/20200120/QOBHhXHWcgBu.jpg
  - https://img.lonuslan.com/lonuslan/20200120/XznCEJWcH0oG.jpg
  - https://img.lonuslan.com/lonuslan/20200120/G0pKoHpLTSqp.jpg
  - https://img.lonuslan.com/lonuslan/20200120/9P2HW1O4DSNl.jpg
  - https://img.lonuslan.com/lonuslan/20200120/IRiGYHISNvks.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 05/06/2020

#social  url, img PC端配置
social:
  github: {url: https://github.com/lonuslan, img: /img/social/github.png}
#  sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
  zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
#  email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
#  wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/lonuslan, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 3002544701
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  mutex: true

# Valine
valine: true
v_appId: cTnjkwAP2P17eijwIUPNU46V-gzGzoHsz
v_appKey: By7MvkQMsK5xU1WTLtrpqx7v

